### ISSUE TITLE
Bug: Undamageable(by players) Carriage causes crash when hit by other sources 

### ISSUE THREAD

**Issue by wildficus** [TheGrimsey/Transportables#10]
**Describe the bug**
DeathDusk Modpack official server is where it happened.
Carriage was immortal, could not be punched or dropped to item.
Phantom hit it with a Shockwave ( Revamped Phantoms) - Server Crash - Issue attached at bottom
Put carriage into lava - Server Crash

**To Reproduce**
Somehow obtain undamageable carriage.
It gets hit by phantom/ put in lava.
Server crash.

**Expected behavior**
If something hits an immune carriage(dont know how to make it immune to player hits) such as an external damage source, server crashes.

**Mod version:**
transportables-1.2
**Fabric API version:**
fabric-api-0.53.4+1.18.2.jar
**Minecraft version:**
1.18.2

**Screenshots**

**Additional Context:**
[crash-2022-05-28_21.26.23-server.txt](https://github.com/TheGrimsey/Transportables/files/8792221/crash-2022-05-28_21.26.23-server.txt)
[crash-2022-05-28_21.42.39-server.txt](https://github.com/TheGrimsey/Transportables/files/8792222/crash-2022-05-28_21.42.39-server.txt)

[Add any other context about the problem here.](https://github.com/lukebemish/revamped_phantoms/issues/9)

**Comment by wildficus** [comment]
https://github.com/lukebemish/revamped_phantoms/issues/9

**Comment by lukebemish** [comment]
I took a look at the crash report and can confirm that this is not caused by Revamped Phantoms. Some mod (possibly this one) has code in LivingEntity#hurt, or puts code there with a mixin, that causes this issue.

**Comment by TheGrimsey** [comment]
> I took a look at the crash report and can confirm that this is not caused by Revamped Phantoms. Some mod (possibly this one) has code in LivingEntity#hurt, or puts code there with a mixin, that causes this issue.

Transportables does not do anything related to ``LivingEntity#hurt``.

As the first crashlog does not relate to Transporables at all I do not think this is related to Transportables. I also **can not** replicate this. It is likely related to another mod.
