### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by lostopkk** [TheGrimsey/Transportables#11]
**Describe the bug**
Crash

**Mod version:**
1.19 version

**Fabric API version:**
0.58.0
**Minecraft version:**
1.19

**Log**
https://www.toptal.com/developers/hastebin/ritoriyaca.properties

**Additional Context:**

**Comment by TheGrimsey** [comment]
This is an issue with Tempad. Been having this exact problem with my own private modpack.
