### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by youngchan01** [TheGrimsey/Transportables#2]
**Describe the bug**
Crash on server start.

**To Reproduce**
1. mods folder: cloth-config-5.0.34-fabric.jar, fabric-api-0.34.10+1.17.jar, transportables-1.0.5.jar
2. Start the Fabric server,
3. get "Failed to launch! Could not find required mod: transportables requires {java @ [>=16]}"

**Expected behavior**
The server should start

**Mod version:**
 transportables-1.0.5.jar

**Fabric API version:**
fabric-api-0.34.10+1.17.jar

**Minecraft version:**
1.17

**Screenshots**
<img width="468" alt="transportables_crash" src="https://user-images.githubusercontent.com/78253722/121649909-99a79280-cacb-11eb-9776-b3251fa3a68f.png">

**Additional Context:**
N/A

**Comment by TheGrimsey** [comment]
You need to install Java 16. This is intended behaviour as Minecraft 1.17 requires Java 16.
