### ISSUE TITLE
Rail and a Tele-Sender

### ISSUE THREAD

**Issue by TheButterbrotMan** [TheGrimsey/Transportables#8]
**Describe the bug**
When you try to link a normal Rail and a Tele-Sender Rail with a Linker.
The game will crash testet on Multiplayer/Singeplayer result the same.

**Mod version:**
1.1
**Fabric API version:**
0.13.3
**Minecraft version:**
1.18.2

**Additional Context:**
https://bytebin.lucko.me/YwBd92vy3Z

**Comment by TheGrimsey** [comment]
Fixed in latest version
https://www.curseforge.com/minecraft/mc-mods/grims-transportables/files/3787169
